services:
  node-app:
    build: .
    container_name: node-app
    ports:
      - 8003:8003
      - 4000:4000
    volumes:
      - .:/app   # 👈 This allows live code reflection
      - /app/node_modules  # Avoid overwriting node_modules
    environment:
      - MONGO_URI=mongodb://admin:admin@mongo:27017
    command: npm run dev 
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
